force-app/main/default/objects/opportunityproductAmountcalculation__c/opportunityproductAmountcalculation__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Amount Calculation</label>
    <nameField>
        <label>OPAC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Product Amount Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/opportunityproductAmountcalculation__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/opportunityproductAmountcalculation__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/opportunityproductAmountcalculation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Product Amount Calculations</relationshipLabel>
    <relationshipName>Opportunity_Product_Amount_Calculations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/oppLineItemTest.cls
@isTest
public class oppLineItemTest {
    @testSetup
    static void setupData(){
        PriceBook2 stpb = new PriceBook2(Id = Test.getStandardPriceBookId(), IsActive = true);
        update stpb;
        PriceBook2 pb = new PriceBook2(Name = 'testPB', IsActive = true);
        insert pb;
        Product2 p = new Product2(Name = 'testProduct', IsActive = true);
        insert p;
        PriceBookEntry pbe = new PriceBookEntry();
        pbe.Product2Id = p.Id;
        pbe.Pricebook2Id = stpb.Id;
        pbe.IsActive = true;
        pbe.UnitPrice = 1000;
        insert pbe;
        Opportunity o = new Opportunity(Name = 'testOpp', Type = 'NewCustomer', 
                                        Amount = 1000, CloseDate = System.Today(), StageName = 'Prospecting');
        insert o;
        OpportunityProductAmountCalculation__c opac = new OpportunityProductAmountCalculation__c();
        opac.Name = 'testOPAC';
        opac.Min__c = 1;
        opac.Max__c = 30;
        opac.Product__c = p.Id;
        opac.Price__c = 300;
        insert opac;
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = o.Id, Product2Id = p.Id, UnitPrice = 10000, Quantity = 10, PricebookEntryId = pbe.Id);
        insert oli;
    }
    @isTest
    static void testCase(){  
    }
}