force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Contact Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactMasterHandler_Undelete.cls
public class ContactMasterHandler_Undelete {
    public void undeleteContactRelationshipsByContact(list<Contact>lstcon){
        set<Id>ContactIds = New set<Id>();
        if(lstcon!=null&&lstcon.size()>0)
        {
            list<Contact_Relationship__c>lstconss = new list<Contact_Relationship__c>();
            lstconss = [Select Id from Contact_Relationship__c Where isDeleted=True and Contact__c In:GlobalUtility.getUniqueIds(lstcon) All ROWS];
            undelete lstconss;
            
            
        }
        
        
        
    }
}