force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Contact Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactMasterHandler.cls
public class ContactMasterHandler {
    public static void createConrealtnbycon(list<Contact>listContact){
        list<Contact_Relationship__c> conlist = new list<Contact_Relationship__c>();
        for(Contact newconlist:listContact){
            if(newconlist.Contact_Relationship__c==true){
                Contact_Relationship__c cr = new Contact_Relationship__c();
                cr.Name= newconlist.FirstName+newconlist.LastName;
                cr.Contact__c=newconlist.Id;
                Conlist.add(cr);
                System.debug(cr.Name);
                System.debug(newconlist.Name);
            }
        }
        if(Conlist.size()>0)
            insert Conlist;
        
    }
    
    
}